name: vdo_ninja
description: Simple capture app for VDO.NInja
version: 5.0.23+23
versionCode: 23

environment:  
  sdk: ">=3.4.0 <4.0.0"
  flutter: 3.27.4

dependencies:  
  camera: ^0.10.0+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.12.8 
  shared_preferences: ^2.0.8
  http: ^1.1.0
  path_provider: ^2.0.2
  wakelock_plus: ^1.2.10
  js: ^0.6.3
  flutter_share: ^2.0.0
  webview_flutter: ^4.2.2
  url_launcher: ^6.0.12
  permission_handler: ^10.4.3
  encrypt: ^5.0.1
  tuple: ^2.0.2
  flutter_background: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
